### ISSUE TITLE
Faces matching and custom face's dataset

### ISSUE THREAD

**Issue by wkouakou** [assemmohamedali/react-native-facerecognition#5]
**Faces matching.**
How can I compare two faces and determine if it is the same person?

**Face's dataset**
I want to create and store face's dataset for authentication.
Is it possible ? How can I do it?
 @assemmohamedali thanks for this module

**Comment by assemmohamedali** [comment]
You will just need to take some photos for both and then use this function onRecognized to get the exact person who shows his face into the camera if he one of the two you stored their faces you will get his name and confidence value.

You can't get your own dataset from the library but maybe in the future I can provide something to generate images dataset but for now, if you need to implement auth into your app just use this library for that task.

**Comment by MartinGao** [comment]
@assemmohamedali thank u for this awesome library!
I am wondering if there was any way for me to somehow "export" the trained data so that I could save those data into my server for authentication purpose?
like right now the only thing I can do is "taking pic and train" but I need to "export" the trained result so next time I could just call the identity method (maybe from another phone)

**Comment by assemmohamedali** [comment]
Yes, I remarked this as enhancement and will be added on the next updates but still I need contributors who have a good knowledge at computer vision at least. I do all the work alone and I got so busy.

I will close the issue if there is another enhancement feel free to make another issue.
